// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Header from "../Header/Header.bs.js";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as TodoItem from "../../components/TodoItem/TodoItem.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var selectItems = [
  {
    id: "1",
    text: "全部"
  },
  {
    id: "2",
    text: "进行中"
  },
  {
    id: "3",
    text: "已完成"
  }
];

function TaskTracker(Props) {
  var match = React.useState(function () {
        return TodoItem.defaultTodos;
      });
  var setTodos = match[1];
  var match$1 = React.useState(function () {
        return selectItems;
      });
  var match$2 = React.useState(function () {
        return "1";
      });
  var setIdx = match$2[1];
  var idx = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setValue = match$3[1];
  var value = match$3[0];
  var addItem = function (todoItem) {
    Curry._1(setTodos, (function (item) {
            return Belt_Array.concat(item, [todoItem]);
          }));
  };
  var deleteItem = function (id) {
    Curry._1(setTodos, (function (item) {
            return item.filter(function (i) {
                        return i.id !== id;
                      });
          }));
  };
  var chanceChecked = function (id) {
    Curry._1(setTodos, (function (item) {
            return item.map(function (i) {
                        if (i.id === id) {
                          return {
                                  id: i.id,
                                  check: !i.check,
                                  text: i.text
                                };
                        } else {
                          return i;
                        }
                      });
          }));
  };
  return React.createElement("div", {
              className: "initBox "
            }, React.createElement(Header.make, {}), React.createElement("div", {
                  className: "iptbox"
                }, React.createElement("input", {
                      className: "ipt",
                      placeholder: "请输入待办事项！",
                      type: "text",
                      value: value,
                      onChange: (function ($$event) {
                          var value = $$event.target.value;
                          Curry._1(setValue, (function (param) {
                                  return value;
                                }));
                        })
                    }), React.createElement("button", {
                      className: "btn",
                      onClick: (function (param) {
                          if (value === "") {
                            console.log("请输入待办事项！！！");
                            return ;
                          }
                          addItem({
                                id: String(Js_math.random_int(0, 1000000)),
                                check: false,
                                text: value
                              });
                          Curry._1(setValue, (function (param) {
                                  return "";
                                }));
                        })
                    }, "添加")), React.createElement("ul", {
                  className: "selectBox"
                }, match$1[0].map(function (s) {
                      return React.createElement("li", {
                                  key: s.id,
                                  className: s.id === idx ? "active" : "",
                                  onClick: (function (param) {
                                      var match = s.id;
                                      switch (match) {
                                        case "2" :
                                            return Curry._1(setIdx, (function (param) {
                                                          return s.id;
                                                        }));
                                        case "3" :
                                            return Curry._1(setIdx, (function (param) {
                                                          return s.id;
                                                        }));
                                        default:
                                          return Curry._1(setIdx, (function (param) {
                                                        return "1";
                                                      }));
                                      }
                                    })
                                }, s.text);
                    })), React.createElement("div", {
                  className: "content"
                }, Belt_Array.keep(match[0], (function (param) {
                          var check = param.check;
                          switch (idx) {
                            case "2" :
                                return !check;
                            case "3" :
                                return check;
                            default:
                              return true;
                          }
                        })).map(function (item) {
                      return React.createElement(TodoItem.make, {
                                  item: item,
                                  deleteItem: deleteItem,
                                  chanceChecked: chanceChecked,
                                  key: item.id
                                });
                    })));
}

var make = TaskTracker;

export {
  selectItems ,
  make ,
}
/* react Not a pure module */
