// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Header(Props) {
  return React.createElement("h2", {
              className: "h2 font_Style"
            }, "Todo List");
}

var make = Header;

export {
  make ,
}
/* react Not a pure module */
