// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TaskTracker from "./pages/taskTracker/TaskTracker.bs.js";

import './styles/App.css';
;

function App(Props) {
  return React.createElement("div", {
              className: "container"
            }, React.createElement(TaskTracker.make, {}));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
